import React, { useState } from 'react';
import './App.css';

function App() {
  const [foto, setFoto] = useState(null);
    const [preview, setPreview] = useState(null);
      const [rapport, setRapport] = useState('');
        const [laden, setLaden] = useState(false);
          const [fout, setFout] = useState('');

            const handleFotoKiezen = (e) => {
                const bestand = e.target.files[0];
                    if (bestand) {
                          setFoto(bestand);
                                setPreview(URL.createObjectURL(bestand));
                                      setRapport('');
                                            setFout('');
                                                }
                                                  };

                                                    const handleAnalyseer = async () => {
                                                        if (!foto) {
                                                              setFout('Kies eerst een foto.');
                                                                    return;
                                                                        }
                                                                            setLaden(true);
                                                                                setFout('');
                                                                                    setRapport('');

                                                                                        try {
                                                                                              const reader = new FileReader();
                                                                                                    reader.readAsDataURL(foto);
                                                                                                          reader.onloadend = async () => {
                                                                                                                  const base64 = reader.result.split(',')[1];
                                                                                                                  
                                                                                                                          const response = await fetch('/api/analyseer', {
                                                                                                                                    method: 'POST',
                                                                                                                                              headers: { 'Content-Type': 'application/json' },
                                                                                                                                                        body: JSON.stringify({ afbeelding: base64, type: foto.type }),
                                                                                                                                                                });
                                                                                                                                                                
                                                                                                                                                                        if (!response.ok) {
                                                                                                                                                                                  const err = await response.json();
                                                                                                                                                                                            throw new Error(err.fout || 'Serverfout');
                                                                                                                                                                                                    }
                                                                                                                                                                                                    
                                                                                                                                                                                                            const data = await response.json();
                                                                                                                                                                                                                    setRapport(data.rapport);
                                                                                                                                                                                                                            setLaden(false);
                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                            setFout(err.message);
                                                                                                                                                                                                                                                  setLaden(false);
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                              <div className="app">
                                                                                                                                                                                                                                                                    <header className="app-header">
                                                                                                                                                                                                                                                                            <h1>Gebouwinspectie AI</h1>
                                                                                                                                                                                                                                                                                    <p>Upload een foto van een gebouw voor een AI-analyse</p>
                                                                                                                                                                                                                                                                                          </header>
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                <main className="app-main">
                                                                                                                                                                                                                                                                                                        <div className="upload-sectie">
                                                                                                                                                                                                                                                                                                                  <label className="upload-label">
                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                            type="file"
                                                                                                                                                                                                                                                                                                                                                          accept="image/*"
                                                                                                                                                                                                                                                                                                                                                                        onChange={handleFotoKiezen}
                                                                                                                                                                                                                                                                                                                                                                                      className="file-input"
                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                              Kies een foto
                                                                                                                                                                                                                                                                                                                                                                                                                        </label>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                        {preview && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="preview-sectie">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src={preview} alt="Preview" className="preview-afbeelding" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={handleAnalyseer}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            disabled={!foto || laden}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="analyseer-knop"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {laden ? 'Analyseren...' : 'Analyseer gebouw'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {fout && <div className="fout-melding">{fout}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {rapport && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="rapport-sectie">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>Inspectierapport</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <pre className="rapport-tekst">{rapport}</pre>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default App;
